### ISSUE TITLE
put experiment-related folder in the Material and method folder ?

### ISSUE THREAD

**Issue by jcolomb** [tonic-team/Tonic-Research-Project-Template#4]

**Comment by deeptimittal12** [comment]
What exactly do you mean experiment-related folder? I am not sure because for example:

I have a specific methods protocol that I use for multple experiments running over a different period of time. I would rather have the standard methods folder and information of each run of experiment in experiment relaed folder. but it really depends on what we put in experiment related folder.

**Comment by jcolomb** [comment]
I meant one folder per experiment, as for data and code. I think we decided against this because in most cases M andM are valid for different experiments. This could be better described in the data folder.

**Comment by jcolomb** [comment]
not for now
